apiVersion: '2018-10-01'
location: uksouth
name: gatling-aci
properties:
  containers:
    - name: gatling
      properties:
        environmentVariables: []
        image: denvazh/gatling
        ports:
          - port: 80
        resources:
          requests:
            cpu: 1.0
            memoryInGB: 1.5
        volumeMounts:
          - mountPath: /opt/gatling/conf
            name: conf
          - mountPath: /opt/gatling/user-files
            name: user-files
          - mountPath: /opt/gatling/results
            name: results
  osType: Linux
  restartPolicy: Never
  ipAddress:
    type: Public
    ports:
      - port: 80
    dnsNameLabel: gatling-test
  volumes:
    - name: conf
      azureFile:
        sharename: conf
        storageAccountName: stgatling
        storageAccountKey: vJLcezqsv+xppQFQ+eVKFBrPNbRWa83Rvc4qYyqDMTCR7AkqY3QUzReHbn+rdUk3tORzJ9Rtv5b3kV7jhlvB5Q==
    - name: user-files
      azureFile:
        sharename: user-files
        storageAccountName: stgatling
        storageAccountKey: vJLcezqsv+xppQFQ+eVKFBrPNbRWa83Rvc4qYyqDMTCR7AkqY3QUzReHbn+rdUk3tORzJ9Rtv5b3kV7jhlvB5Q==
    - name: results
      azureFile:
        sharename: results
        storageAccountName: stgatling
        storageAccountKey: vJLcezqsv+xppQFQ+eVKFBrPNbRWa83Rvc4qYyqDMTCR7AkqY3QUzReHbn+rdUk3tORzJ9Rtv5b3kV7jhlvB5Q==

tags: {}
type: Microsoft.ContainerInstance/containerGroups